### ISSUE TITLE
Align stacks

### ISSUE THREAD

**Issue by hongzhan2015** [turonova/novaCTF#4]
Hihi, 
I am going to do step 3, and for alignment, are you using imod function? should be doing coarse alignment is enough or should do fine alignment? 

Many thanks!
Hong

**Comment by turonova** [comment]
Yes, we typically use the IMOD newstack function that we provide with transform file (typically with .xf extension). The transform file is created during the fine alignment in IMOD (we do the alignment in eTomo on the original stack and then we use the transform file for all the CTF-corrected stacks). The coarse alignment quality strongly depends on the quality of your data but in order to achieve a good alignment (and also the resolution in the end) you should do also the fine alignment.

**Comment by hongzhan2015** [comment]
Great thanks! And one stupid question and I am new to this field... I used ctffind4 to get defocus file, and there is two output, one is *.txt, the other is *_avg.txt. The latter one is used to draw plot to estimate the resolution and fitting quality checking. I assume I should use avg file? Many thanks again!

**Comment by turonova** [comment]
You should use the .txt file - more on how it should look like can be found [here](https://github.com/turonova/novaCTF/issues/2).

**Comment by hongzhan2015** [comment]
Thanks for the answer!
