### ISSUE TITLE
Striping in reconstruction

### ISSUE THREAD

**Issue by damsport11** [turonova/novaCTF#6]
Hi,

We are having issues with NovaCTF where the final reconstructions show a horizontal striping pattern (see images below). As an input we used the alligned unbinned tilt series followed by CTF determination with ctfFind4, defocus file generation, CTF correction of alligned tilt series, flipyz of the CTF corrected tilt series followed by 3dctf reconstruction. 
We have tried to reconstruct several tilt series this way, but all have these stripes patterns. What could explain this pattern and what could we do to avoid it?

![novactf_output](https://user-images.githubusercontent.com/25221329/33436000-03d4a584-d5e4-11e7-991e-6134f703dfc6.png)

`novaCTF \
		-Algorithm defocus \
		-InputProjections IS002_291013_005.mrcs \
		-FULLIMAGE 3838,3710 \
		-THICKNESS 500 \
		-TILTFILE IS002_291013_005.tlt \
		-SHIFT 0.0,0.0 \
		-CorrectionType multiplication \
		-DefocusFileFormat ctffind4 \
		-CorrectAstigmatism 1 \
		-DefocusFile defocus_file.txt \
		-PixelSize 0.2276 \
		-DefocusStep 30 &`

`		novaCTF \
		-Algorithm ctfCorrection \
		-InputProjections $v_inputprojections \
		-OutputFile corrected_stack.st_${i} \
		-DefocusFile defocus_file.txt_${i} \
		-TILTFILE IS002_291013_005.tlt \
		-CorrectionType multiplication \
		-DefocusFileFormat ctffind4 \
		-CorrectAstigmatism 1 \
		-PixelSize 0.2276 \
		-AmplitudeContrast 0.07 \
		-Cs 2.7 \
		-Volt 200 &
`

`clip flipyz corrected_stack.st_${i} corrected_stack_flipped.ali_${i} `

`		novaCTF \
		-Algorithm 3dctf \
		-InputProjections corrected_stack_flipped.ali \
		-OutputFile Tomogram_005.rec \
		-TILTFILE IS002_291013_005.tlt \
		-THICKNESS 500 \
		-FULLIMAGE 3838,3710 \
		-SHIFT 0.0,0.0 -PixelSize 0.2276 -DefocusStep 30
`
Thank you very much in advance for your help again.

Casper Berger & Kevin Knoops
Maastricht University

**Comment by turonova** [comment]
How do the tilt-series look like after CTF correction step? Can you maybe at some (high) tilts see something similar as [in this question](https://github.com/turonova/novaCTF/issues/5)? You do not have squared images and there was a bug regarding that which was fixed in the meantime (10 days ago). If you can observe stripes in your CTF-corrected stacks and you do not have the latest version then please download it and try again. 

Otherwise, you also have to filter prior the reconstruction (see the workflow [here](https://github.com/turonova/novaCTF/wiki/CTF-Correction-workflow-overview)) otherwise you perform only back projection which will always result in very blurry images (the "ghosts" in such tomograms are always more visible and the tomograms look more "stripy").

The parameters look fine to me and the right image is not so bad, although the alignment is not so good.
